/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "omip.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(omip_WrapperMessage, omip_WrapperMessage, AUTO)


PB_BIND(omip_InputDigital, omip_InputDigital, AUTO)


PB_BIND(omip_InputAnalog, omip_InputAnalog, AUTO)


PB_BIND(omip_InputEncoder, omip_InputEncoder, AUTO)


PB_BIND(omip_FeedbackImage, omip_FeedbackImage, AUTO)


PB_BIND(omip_FeedbackLed, omip_FeedbackLed, AUTO)


PB_BIND(omip_SystemConfig, omip_SystemConfig, AUTO)


PB_BIND(omip_DeviceCapabilityRequest, omip_DeviceCapabilityRequest, AUTO)


PB_BIND(omip_DeviceCapabilityResponse, omip_DeviceCapabilityResponse, AUTO)


PB_BIND(omip_DeviceCapabilityResponse_PortDescription, omip_DeviceCapabilityResponse_PortDescription, AUTO)







